"""
================================================================================
PaleoAST - Global Exception Handler
================================================================================

本模块实现全局异常拦截与日志系统，确保应用程序绝不闪退。

作者: PaleoAST Development Team
"""

import logging
import os
import platform
import socket
import sys
import traceback
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import psutil
from PyQt6.QtCore import QObject, pyqtSignal
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import (
    QApplication,
    QDialog,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QMessageBox,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from config.i18n import _

logger = logging.getLogger(__name__)


@dataclass
class ExceptionInfo:
    """异常信息"""

    id: str
    timestamp: str
    exception_type: str
    exception_value: str
    traceback_text: str
    stack_summary: str
    system_info: dict
    application_state: str | None = None
    user_message: str | None = None
    handled: bool = False

    def get_full_report(self) -> str:
        """获取完整报告"""
        return f"""
================================================================================
PaleoAST Critical Error Report
================================================================================

Report ID: {self.id}
Timestamp: {self.timestamp}

--------------------------------------------------------------------------------
EXCEPTION INFORMATION
--------------------------------------------------------------------------------

Exception Type: {self.exception_type}
Exception Value: {self.exception_value}

--------------------------------------------------------------------------------
SYSTEM INFORMATION
--------------------------------------------------------------------------------

Platform: {self.system_info.get("platform", "Unknown")}
OS: {self.system_info.get("os", "Unknown")}
Python Version: {self.system_info.get("python_version", "Unknown")}
Architecture: {self.system_info.get("architecture", "Unknown")}
Processor: {self.system_info.get("processor", "Unknown")}
Machine: {self.system_info.get("machine", "Unknown")}

--------------------------------------------------------------------------------
ENVIRONMENT
--------------------------------------------------------------------------------

CPU Count: {self.system_info.get("cpu_count", "Unknown")}
CPU Usage: {self.system_info.get("cpu_percent", "Unknown")}
Memory Total: {self.system_info.get("memory_total", "Unknown")}
Memory Available: {self.system_info.get("memory_available", "Unknown")}
Memory Percent: {self.system_info.get("memory_percent", "Unknown")}

Current Working Directory: {self.system_info.get("cwd", "Unknown")}
Hostname: {self.system_info.get("hostname", "Unknown")}

--------------------------------------------------------------------------------
COMPLETE TRACEBACK
--------------------------------------------------------------------------------

{self.traceback_text}

--------------------------------------------------------------------------------
STACK SUMMARY
--------------------------------------------------------------------------------

{self.stack_summary}

--------------------------------------------------------------------------------
APPLICATION STATE
--------------------------------------------------------------------------------

{self.application_state or "Not available"}

================================================================================
This report was generated by PaleoAST Error Handler
Please save this report and contact support if the problem persists.
================================================================================
"""


class SystemInfoCollector:
    """
    系统信息收集器

    收集详细的系统环境信息用于错误报告。
    """

    @staticmethod
    def collect() -> dict:
        """
        收集系统信息

        返回:
            系统信息字典
        """
        info = {}

        try:
            # 平台信息
            info["platform"] = sys.platform
            info["os"] = f"{platform.system()} {platform.release()}"
            info["python_version"] = sys.version
            info["architecture"] = platform.machine()
            info["processor"] = platform.processor()
            info["machine"] = platform.node()

            # CPU信息
            info["cpu_count"] = psutil.cpu_count(logical=True)
            info["cpu_percent"] = f"{psutil.cpu_percent(interval=0.1)}%"

            # 内存信息
            mem = psutil.virtual_memory()
            info["memory_total"] = SystemInfoCollector._format_bytes(mem.total)
            info["memory_available"] = SystemInfoCollector._format_bytes(mem.available)
            info["memory_percent"] = f"{mem.percent}%"

            # 网络信息
            try:
                info["hostname"] = socket.gethostname()
                info["ip_address"] = socket.gethostbyname(socket.gethostname())
            except OSError as e:
                logger.debug(f"Could not get network info: {e}")
                info["hostname"] = "Unknown"
                info["ip_address"] = "Unknown"

            # 路径信息
            info["cwd"] = os.getcwd()
            info["home"] = os.path.expanduser("~")
            info["temp"] = os.environ.get("TEMP", "/tmp")

            # 环境变量 (只收集非敏感信息)
            info["path_entries"] = len(os.environ.get("PATH", "").split(os.pathsep))

            # 显示器信息
            try:
                from PyQt6.QtWidgets import QApplication

                app = QApplication.instance()
                if app:
                    screen = app.primaryScreen()
                    if screen:
                        info["screen_resolution"] = f"{screen.geometry().width()}x{screen.geometry().height()}"
                        info["screen_dpi"] = str(screen.logicalDotsPerInch())
            except Exception as e:
                logger.debug(f"Could not get screen resolution: {e}")

        except Exception as e:
            logger.error(f"Error collecting system info: {e}")
            info["error"] = str(e)

        return info

    @staticmethod
    def _format_bytes(bytes_value: int) -> str:
        """格式化字节数"""
        for unit in ["B", "KB", "MB", "GB", "TB"]:
            if bytes_value < 1024:
                return f"{bytes_value:.2f} {unit}"
            bytes_value /= 1024
        return f"{bytes_value:.2f} PB"


class CrashReportDialog(QDialog):
    """
    崩溃报告对话框

    显示详细的错误信息并提供导出功能。
    """

    def __init__(self, exception_info: ExceptionInfo, parent: QWidget | None = None):
        """
        初始化崩溃报告对话框

        参数:
            exception_info: 异常信息
            parent: 父窗口
        """
        super().__init__(parent)

        self._exception_info = exception_info
        self._is_expanded = False

        self._init_ui()
        self._populate_data()

    def _init_ui(self) -> None:
        """初始化UI"""
        self.setWindowTitle("PaleoAST - Critical Error")
        self.setMinimumSize(700, 500)
        self.setModal(True)

        # 主布局
        main_layout = QVBoxLayout(self)
        main_layout.setSpacing(15)
        main_layout.setContentsMargins(20, 20, 20, 20)

        # 标题区域
        title_label = QLabel("⚠️  Application Error Detected")
        title_label.setFont(QFont("Segoe UI", 16, QFont.Weight.Bold))
        title_label.setStyleSheet("color: #E74C3C;")

        # 说明标签
        info_label = QLabel(
            "PaleoAST encountered a critical error and needs to continue operation. "
            "Please review the error details below and click 'Export Report' to save the error log."
        )
        info_label.setWordWrap(True)
        info_label.setStyleSheet("color: #95A5A6;")

        # 错误摘要
        summary_group = QGroupBox("Error Summary")
        summary_layout = QVBoxLayout(summary_group)

        self._type_label = QLabel()
        self._type_label.setFont(QFont("Consolas", 10, QFont.Weight.Bold))
        self._type_label.setStyleSheet("color: #E74C3C;")

        self._message_label = QLabel()
        self._message_label.setWordWrap(True)
        self._message_label.setStyleSheet("color: #ECF0F1;")

        summary_layout.addWidget(self._type_label)
        summary_layout.addWidget(self._message_label)

        # 详细信息区域 (可折叠)
        details_group = QGroupBox("Technical Details (Click to Expand)")
        details_layout = QVBoxLayout(details_group)

        # 系统信息
        self._system_info_text = QTextEdit()
        self._system_info_text.setReadOnly(True)
        self._system_info_text.setMaximumHeight(150)
        self._system_info_text.setFont(QFont("Consolas", 8))
        self._system_info_text.setStyleSheet("""
            QTextEdit {
                background-color: #2C3E50;
                color: #ECF0F1;
                border: 1px solid #34495E;
                border-radius: 4px;
                padding: 8px;
            }
        """)

        # Traceback
        self._traceback_text = QTextEdit()
        self._traceback_text.setReadOnly(True)
        self._traceback_text.setFont(QFont("Consolas", 8))
        self._traceback_text.setStyleSheet(self._system_info_text.styleSheet())

        details_layout.addWidget(QLabel("System Information:"))
        details_layout.addWidget(self._system_info_text)
        details_layout.addWidget(QLabel("Complete Traceback:"))
        details_layout.addWidget(self._traceback_text)

        # 按钮区域
        button_layout = QHBoxLayout()
        button_layout.addStretch()

        # 复制按钮
        copy_btn = QPushButton("📋 Copy to Clipboard")
        copy_btn.setObjectName("primary")
        copy_btn.clicked.connect(self._copy_to_clipboard)

        # 导出按钮
        export_btn = QPushButton("📁 Export Report")
        export_btn.setObjectName("success")
        export_btn.clicked.connect(self._export_report)

        # 继续按钮
        continue_btn = QPushButton("▶ Continue Anyway")
        continue_btn.clicked.connect(self.accept)

        # 退出按钮
        quit_btn = QPushButton("❌ Quit")
        quit_btn.setObjectName("danger")
        quit_btn.clicked.connect(self._quit_application)

        button_layout.addWidget(copy_btn)
        button_layout.addWidget(export_btn)
        button_layout.addWidget(continue_btn)
        button_layout.addWidget(quit_btn)

        # 添加到主布局
        main_layout.addWidget(title_label)
        main_layout.addWidget(info_label)
        main_layout.addWidget(summary_group)
        main_layout.addWidget(details_group, stretch=1)
        main_layout.addLayout(button_layout)

    def _populate_data(self) -> None:
        """填充数据"""
        self._type_label.setText(f"Type: {self._exception_info.exception_type}")
        self._message_label.setText(f"Message: {self._exception_info.exception_value}")

        # 系统信息
        system_info = self._exception_info.system_info
        system_lines = []
        for key, value in system_info.items():
            system_lines.append(f"  {key}: {value}")
        self._system_info_text.setPlainText("\n".join(system_lines))

        # Traceback
        self._traceback_text.setPlainText(self._exception_info.traceback_text)

    def _copy_to_clipboard(self) -> None:
        """复制到剪贴板"""
        clipboard = QApplication.clipboard()
        clipboard.setText(self._exception_info.get_full_report())

        # 显示提示
        QMessageBox.information(self, _("Copied"), _("Error report copied to clipboard!"))

    def _export_report(self) -> None:
        """导出报告"""
        from PyQt6.QtWidgets import QFileDialog

        # 获取默认文件名
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        default_name = f"paleoast_crash_report_{timestamp}.txt"

        # 显示保存对话框
        file_path, _ = QFileDialog.getSaveFileName(
            self,
            _("Export Crash Report"),
            str(Path.home() / "Desktop" / default_name),
            _("Text Files (*.txt);;All Files (*)"),
        )

        if file_path:
            try:
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(self._exception_info.get_full_report())

                QMessageBox.information(self, _("Export Successful"), _("Report exported to:\n{0}").format(file_path))
            except Exception as e:
                QMessageBox.critical(self, _("Export Failed"), _("Failed to export report:\n{0}").format(e))

    def _quit_application(self) -> None:
        """退出应用程序.

        ``QApplication.quit()`` only schedules a quit event on the
        event loop, which is harmless from the GUI thread but is
        unreliable when invoked from a worker thread or from a
        dialog's signal handler where the event loop is already
        inside ``exec()``. Use ``QApplication.exit(1)`` instead so
        the process tears down immediately and returns a non-zero
        exit code to the OS.
        """
        self.reject()
        QApplication.exit(1)


class GlobalExceptionHandler(QObject):
    """
    全局异常处理器

    捕获所有未处理的异常并显示友好的错误报告。

    使用示例:
        >>> handler = GlobalExceptionHandler()
        >>> handler.install()
        >>> # 或者只安装QThread的
        >>> handler.install_qt_exception_handler()
    """

    # 信号
    exception_occurred = pyqtSignal(ExceptionInfo)

    def __init__(self):
        """初始化异常处理器"""
        super().__init__()

        self._original_excepthook = None
        self._original_qt_exception = None
        self._is_installed = False
        self._suppress_next_exception = False
        self._exception_callback: Callable[[ExceptionInfo], Any] | None = None
        self._log_file: Path | None = None

        # 设置日志文件
        self._setup_log_file()

        logger.info("GlobalExceptionHandler initialized")

    def _setup_log_file(self) -> None:
        """设置日志文件"""
        try:
            log_dir = Path.home() / ".paleoast" / "logs"
            log_dir.mkdir(parents=True, exist_ok=True)

            # 保留最近7天的日志
            self._log_file = log_dir / f"paleoast_{datetime.now().strftime('%Y%m%d')}.log"

            # 配置文件处理器
            file_handler = logging.FileHandler(self._log_file, encoding="utf-8")
            file_handler.setLevel(logging.DEBUG)
            file_handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))

            # 添加到根日志记录器
            logging.getLogger().addHandler(file_handler)

            logger.info(f"Log file: {self._log_file}")
        except Exception as e:
            logger.error(f"Failed to setup log file: {e}")

    def _collect_exception_info(self, exc_type: type, exc_value: BaseException, exc_tb) -> ExceptionInfo:
        """
        收集异常信息

        参数:
            exc_type: 异常类型
            exc_value: 异常值
            exc_tb: 异常回溯

        返回:
            ExceptionInfo
        """
        # 生成唯一ID
        exc_id = str(uuid.uuid4())[:8]

        # 获取时间戳
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]

        # 获取完整traceback
        tb_text = "".join(traceback.format_exception(exc_type, exc_value, exc_tb))

        # 获取栈摘要
        stack_summary = traceback.format_exc()

        # 收集系统信息
        system_info = SystemInfoCollector.collect()

        # 获取应用状态
        app_state = None
        try:
            app = QApplication.instance()
            if app:
                windows = app.topLevelWidgets()
                app_state = f"Active Windows: {len(windows)}\n"
                for i, w in enumerate(windows[:5]):
                    app_state += f"  {i + 1}. {w.__class__.__name__}: {w.windowTitle()}\n"
        except Exception as e:
            logger.debug(f"Could not get application state: {e}")

        return ExceptionInfo(
            id=exc_id,
            timestamp=timestamp,
            exception_type=exc_type.__name__ if exc_type else "Unknown",
            exception_value=str(exc_value),
            traceback_text=tb_text,
            stack_summary=stack_summary,
            system_info=system_info,
            application_state=app_state,
        )

    def _handle_exception(self, exc_info: tuple) -> None:
        """
        处理异常

        参数:
            exc_info: (type, value, traceback) 元组
        """
        exc_type, exc_value, exc_tb = exc_info

        # 检查是否应忽略
        if self._suppress_next_exception:
            self._suppress_next_exception = False
            return

        # 记录到日志
        logger.critical(f"Unhandled exception: {exc_type.__name__}: {exc_value}", exc_info=exc_info)

        # 收集详细信息
        exception_info = self._collect_exception_info(exc_type, exc_value, exc_tb)

        # 发送信号
        self.exception_occurred.emit(exception_info)

        # 调用回调
        if self._exception_callback:
            try:
                self._exception_callback(exception_info)
            except Exception as e:
                logger.error(f"Exception in callback: {e}")

        # 显示GUI对话框
        self._show_crash_dialog(exception_info)

    def _show_crash_dialog(self, exception_info: ExceptionInfo) -> None:
        """显示崩溃对话框"""
        try:
            app = QApplication.instance()
            if app:
                # 确保在主线程中显示
                dialog = CrashReportDialog(exception_info)
                result = dialog.exec()

                if result == QDialog.DialogCode.Rejected:
                    # 用户选择退出
                    logger.info("User chose to quit application")
                    app.quit()
        except Exception as e:
            logger.error(f"Failed to show crash dialog: {e}")
            # 降级到命令行输出
            print("=" * 80)
            print("CRITICAL ERROR:")
            print(exception_info.get_full_report())
            print("=" * 80)

    def _excepthook(self, exc_type: type, exc_value: BaseException, exc_tb) -> None:
        """
        Python全局异常钩子

        参数:
            exc_type: 异常类型
            exc_value: 异常值
            exc_tb: 异常回溯
        """
        if exc_type is KeyboardInterrupt:
            # 允许用户中断
            sys.__excepthook__(exc_type, exc_value, exc_tb)
            return

        # 调用处理
        self._handle_exception((exc_type, exc_value, exc_tb))

    def install(self) -> None:
        """安装全局异常处理器"""
        if self._is_installed:
            logger.warning("Exception handler already installed")
            return

        # 保存原始钩子
        self._original_excepthook = sys.excepthook

        # 安装新钩子
        sys.excepthook = self._excepthook

        self._is_installed = True
        logger.info("Global exception handler installed")

    def uninstall(self) -> None:
        """卸载全局异常处理器"""
        if not self._is_installed:
            return

        # 恢复原始钩子
        if self._original_excepthook:
            sys.excepthook = self._original_excepthook

        self._is_installed = False
        logger.info("Global exception handler uninstalled")

    def set_exception_callback(self, callback: Callable[[ExceptionInfo], Any]) -> None:
        """
        设置异常回调

        参数:
            callback: 回调函数
        """
        self._exception_callback = callback

    def suppress_next(self) -> None:
        """抑制下一次异常"""
        self._suppress_next_exception = True

    @property
    def is_installed(self) -> bool:
        """是否已安装"""
        return self._is_installed

    @property
    def log_file(self) -> Path | None:
        """获取日志文件路径"""
        return self._log_file


# 全局实例
_global_handler: GlobalExceptionHandler | None = None


def get_global_exception_handler() -> GlobalExceptionHandler:
    """
    获取全局异常处理器实例

    返回:
        GlobalExceptionHandler
    """
    global _global_handler

    if _global_handler is None:
        _global_handler = GlobalExceptionHandler()

    return _global_handler


def install_global_exception_handler() -> GlobalExceptionHandler:
    """
    安装全局异常处理器

    返回:
        GlobalExceptionHandler
    """
    handler = get_global_exception_handler()
    handler.install()
    return handler
