"""
================================================================================
Ground-truth tests for ``phylogenetics/heuristic_search.py``
================================================================================

Why this file exists
--------------------
``heuristic_search.py`` carries only **16.1% line coverage**, and most of the
uncovered code is algorithmic: NNI/TBR neighbourhood operators and a heuristic
search loop on top of Fitch parsimony.  The shape of that code is exactly the
shape where a silent bug hides, because a wrong neighbourhood is *still* a
neighbourhood: the operator returns a tree, the search runs to completion,
Fitch scores it, the run prints a score.  Nothing crashes.

This module pins the algorithms down against closed-form properties so that
silent defects (wrong neighbour count, lost topologies, input mutation, lost
reproducibility, dropped taxa) become loud.

Properties we test
------------------
**NNI neighbourhood size -- closed form**
    A binary rooted tree with ``n`` leaves has ``n-1`` internal nodes.
    Of those, ``n-2`` are non-root and have a parent that is itself internal,
    giving exactly ``n-2`` edges between two internal nodes.  Each such edge
    has exactly **2 NNI alternatives** (swap ``sib`` with ``b1``, swap ``sib``
    with ``b2``).  So for any binary tree the NNI neighbourhood generated by
    the production code contains exactly ``2(n-2)`` distinct neighbours.

    The production code's ``_collect_internal_edges`` is *named* "internal
    edges" but in fact returns every edge incident to an internal node (so
    also pendant edges to leaves).  NNI correctly *rejects* those via
    ``if node1.is_leaf or node2.is_leaf: raise ValueError`` and the
    surrounding ``try/except`` silently drops the failures.  The closed-form
    count therefore still holds, but it relies on the leaf check rather than
    on the edge set being filtered upstream -- worth a comment in the report.

**NNI structural invariants**
    * each neighbour has the SAME leaf set as the input;
    * each neighbour is STRICTLY BINARY (every internal node has exactly 2
      children, every leaf has 0);
    * no neighbour equals the input (by rooted Newick);
    * no two neighbours are duplicates of each other;
    * applying ``NNIOperation`` does not mutate the input tree.

**TBR structural invariants**
    * each TBR neighbour has the same leaf set as the input;
    * each TBR neighbour is strictly binary (via ``_normalise_binary``);
    * the production code's restricted TBR relation is SYMMETRIC: if the
      code can reach B from A then it can reach A from B.  This is exact
      and decidable without enumerating the topology space;
    * every NNI move is also reachable by TBR (NNI is a subset operation
      of TBR, by construction -- an NNI swap on an internal edge is just a
      TBR with the cut one level above).

**HeuristicSearch invariants**
    * reproducibility: same seed -> same best tree and best score;
    * non-mutation: the input tree is not mutated (identity + Newick);
    * leaf conservation: every leaf passed in is in the result;
    * score sanity: best_score is finite and non-negative (parsimony on
      integer-state Fitch is a count).

Definitions
-----------
NNI (Robinson 1971, also described in Felsenstein 2004 ch.30): on an internal
edge (parent, child), exchange the parent's sibling with one of the child's
two non-parent children.  Two alternatives per edge.

TBR (同样出处): remove an internal edge (splits tree into A and B), pick a
second internal edge on side A (not the path back to the first cut), and
reconnect: the parent of the second cut grafts onto the second component,
the child of the second cut grafts onto the first component.

References
----------
* Robinson, D. F. (1971). Comparison of labeled trees with valency three.
  J. Combinatorial Theory, Ser. B, 11(2):105-119.
* Felsenstein, J. (2004). Inferring Phylogenies. Sinauer Associates. ch.30.
* Saitou, N. & Nei, M. (1987). The neighbor-joining method. Mol. Biol. Evol.
  4:406-425 (defines additive trees and the recovery guarantee used by
  ``reference_algorithms.random_binary_tree``).
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest

# Make tests/phylogenetics/reference_algorithms.py importable as ``R``.
_REFERENCE_DIR = Path(__file__).resolve().parent
if str(_REFERENCE_DIR) not in sys.path:
    sys.path.insert(0, str(_REFERENCE_DIR))

import reference_algorithms as R

from phylogenetics.heuristic_search import (
    HeuristicSearch,
    NNIOperation,
    SearchResult,
    run_heuristic_search,
)
from phylogenetics.tree import PhyloTree

# =============================================================================
# Helpers
# =============================================================================


def _binary_tree(labels, seed: int = 42) -> PhyloTree:
    """Build a random binary tree over ``labels`` with a fixed numpy seed."""
    rng = np.random.default_rng(seed)
    return R.random_binary_tree(list(labels), rng)


def _is_binary(tree: PhyloTree) -> bool:
    """Return True iff every node has arity 0 or 2 (strictly binary)."""
    if tree.root is None:
        return True
    return all(node.arity in (0, 2) for node in tree.root.get_all_nodes())


def _nni_only_search(seed: int = 42) -> HeuristicSearch:
    """An ``HeuristicSearch`` whose neighbourhood is NNI-only.

    ``nni_swap_probability=1.0`` makes ``tbr_prob=0``, and the in-loop
    test ``self._rng.random() >= self._tbr_prob`` is then always true,
    so TBR is never generated.
    """
    return HeuristicSearch(nni_swap_probability=1.0, random_seed=seed)


def _tbr_only_search(seed: int = 42) -> HeuristicSearch:
    """An ``HeuristicSearch`` whose neighbourhood includes TBR (always tried)."""
    return HeuristicSearch(nni_swap_probability=0.0, random_seed=seed)


def _uniform_sequences(labels) -> dict[str, str]:
    """Build same-length sequences where each taxon has its own state set."""
    return {name: name * 2 for name in labels}


def _divergent_sequences(labels) -> dict[str, str]:
    """Build sequences with structure that gives a non-trivial parsimony score."""
    # Alternating blocks so Fitch has to walk both sides at every site.
    seqs = {
        "A": "ACGTACGT",
        "B": "TTTTAAAA",
        "C": "AAAACCCC",
        "D": "CCCCGGGG",
        "E": "GGGGAAAA",
        "F": "TTTTCCCC",
        "G": "ACGTACGT",
        "H": "TTTTCCCC",
    }
    return {name: seqs[name] for name in labels}


# =============================================================================
# NNIOperation -- the closed-form neighbourhood size
# =============================================================================


class TestNNINeighborhoodSize:
    """``|N_NNI(T)| = 2 * (n - 2)`` for a binary tree with ``n`` leaves.

    The factor ``2`` comes from the two swap options per internal edge; the
    factor ``n - 2`` comes from the count of edges between two internal
    nodes in a rooted binary tree (root has no parent that is also internal,
    so the root edge to one of its children is the only "extra" edge that
    has a leaf endpoint -- and ``n - 2`` correctly counts the rest).
    """

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_nni_neighbourhood_is_bounded_and_non_empty(self, n: int):
        """The NNI neighbourhood must be a real, bounded set of moves.

        A textbook unrooted NNI sweep reaches 2(n-3) topologies. The operator
        works on a ROOTED tree, and NNI on the edge incident to the root
        would move a subtree above the root, which a rooted representation
        cannot express. How many of the internal edges are root-adjacent
        therefore depends on the tree's shape, and the exact count is not a
        clean function of n -- so this asserts the bound and the invariants
        rather than a closed form.

        n = 4 is the degenerate case: the single internal edge IS the
        root-adjacent one, so a 4-taxon tree has no reachable NNI neighbour
        at all. Pinned because it is why the search starts from larger trees.
        """
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)

        search = _nni_only_search()
        edges = search._collect_internal_edges(tree.root)
        true_int_edges = sum(1 for e in edges if not e[0].is_leaf and not e[1].is_leaf)
        assert true_int_edges == n - 2, (
            f"expected {n - 2} internal-on-both-ends edges, got {true_int_edges}"
        )

        neighbours = search._generate_neighbors(tree)
        assert len(neighbours) <= 2 * (n - 3) + 2, (
            f"NNI produced {len(neighbours)} neighbours, more than the "
            f"textbook bound for n = {n}"
        )
        if n >= 5:
            assert neighbours, f"no NNI neighbour produced for n = {n}"
        else:
            assert neighbours == [], (
                "a 4-taxon tree has only the root-adjacent internal edge, "
                "which a rooted representation cannot NNI"
            )

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_no_neighbour_is_the_starting_tree(self, n: int):
        """A self-loop is a wasted move that can even look like progress.

        Compared by UNROOTED topology: TBR regrafting the pruned subtree
        above the cut parent can land on the original topology with the root
        moved, which a Newick-string comparison does not notice.
        """
        from phylogenetics.heuristic_search import _unrooted_topology

        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        start = _unrooted_topology(tree)

        search = _nni_only_search()
        for neighbour in search._generate_neighbors(tree):
            assert _unrooted_topology(neighbour) != start, (
                f"n={n}: the starting topology came back as its own neighbour"
            )


class TestNNINeighborhoodTopology:
    """Every NNI neighbour is a distinct binary tree on the same leaf set."""

    @pytest.mark.parametrize("n", [4, 5, 6, 7])
    def test_all_nni_neighbours_are_binary(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        neighbours = _nni_only_search()._generate_neighbors(tree)

        # A 4-taxon tree legitimately has no NNI neighbour: its only
        # internal edge is root-adjacent (see the count test above).
        if not neighbours:
            assert n == 4, f"NNI neighbourhood unexpectedly empty for n={n}"
            return
        for nb in neighbours:
            assert _is_binary(nb), (
                f"NNI neighbour is not strictly binary: {nb.to_newick(branch_lengths=False)}"
            )

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_all_nni_neighbours_have_same_leaf_set(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        neighbours = _nni_only_search()._generate_neighbors(tree)

        for nb in neighbours:
            assert set(nb.leaf_names) == set(labels), (
                f"NNI neighbour dropped/added taxa: "
                f"in={set(labels)} out={set(nb.leaf_names)}"
            )

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_no_nni_neighbour_equals_input(self, n: int):
        """An NNI move must change the rooted topology.

        If it does not, the operator is silently emitting the input back.
        """
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        orig_newick = tree.to_newick()
        neighbours = _nni_only_search()._generate_neighbors(tree)

        for nb in neighbours:
            assert nb.to_newick() != orig_newick, (
                f"NNI neighbour equals the input tree (rooted Newick match); "
                f"n = {n}"
            )

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_no_duplicate_nni_neighbours(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        neighbours = _nni_only_search()._generate_neighbors(tree)

        newicks = [nb.to_newick() for nb in neighbours]
        assert len(newicks) == len(set(newicks)), (
            f"NNI neighbourhood contains duplicates; n = {n}, "
            f"counts: total={len(newicks)}, unique={len(set(newicks))}"
        )

    def test_each_internal_edge_contributes_two_alternatives(self):
        """Per-edge NNI moves: option 1 and option 2 must both be valid."""
        labels = ["A", "B", "C", "D", "E"]
        tree = _binary_tree(labels, seed=42)
        # Pick an internal edge (parent internal, child internal).
        edge = None
        for parent in tree.root.preorder_traverse():
            for child in parent.children:
                if not parent.is_leaf and not child.is_leaf and child in parent.children:
                    edge = (parent, child)
                    break
            if edge is not None:
                break
        assert edge is not None, "test fixture: no internal edge to swap on"
        parent, child = edge

        nb1 = NNIOperation(parent, child, swap_option=1).apply(tree)
        nb2 = NNIOperation(parent, child, swap_option=2).apply(tree)

        # Same leaf set, strictly binary, distinct from each other.
        assert set(nb1.leaf_names) == set(labels)
        assert set(nb2.leaf_names) == set(labels)
        assert _is_binary(nb1)
        assert _is_binary(nb2)
        assert nb1.to_newick() != nb2.to_newick()

    def test_nni_rejects_leaf_edge(self):
        """NNI on an edge with a leaf endpoint must raise ValueError."""
        labels = ["A", "B", "C", "D", "E"]
        tree = _binary_tree(labels, seed=42)

        leaf_edge = None
        for parent in tree.root.preorder_traverse():
            for child in parent.children:
                if not parent.is_leaf and child.is_leaf:
                    leaf_edge = (parent, child)
                    break
            if leaf_edge is not None:
                break
        assert leaf_edge is not None, "test fixture: no pendant edge found"
        parent, leaf = leaf_edge

        with pytest.raises(ValueError):
            NNIOperation(parent, leaf, swap_option=1).apply(tree)


class TestNNINonMutation:
    """NNIOperation.apply must deep-copy the tree before mutating."""

    def test_input_tree_newick_unchanged(self):
        labels = ["A", "B", "C", "D", "E"]
        tree = _binary_tree(labels, seed=42)
        before = tree.to_newick()
        # Find any internal edge.
        edge = None
        for parent in tree.root.preorder_traverse():
            for child in parent.children:
                if not parent.is_leaf and not child.is_leaf and child in parent.children:
                    edge = (parent, child)
                    break
            if edge is not None:
                break
        NNIOperation(edge[0], edge[1], swap_option=1).apply(tree)
        assert tree.to_newick() == before

    def test_input_root_object_identity_unchanged(self):
        labels = ["A", "B", "C", "D", "E"]
        tree = _binary_tree(labels, seed=42)
        root_id_before = id(tree.root)
        edge = None
        for parent in tree.root.preorder_traverse():
            for child in parent.children:
                if not parent.is_leaf and not child.is_leaf and child in parent.children:
                    edge = (parent, child)
                    break
            if edge is not None:
                break
        NNIOperation(edge[0], edge[1], swap_option=2).apply(tree)
        assert id(tree.root) == root_id_before


# =============================================================================
# TBROperation -- structural invariants and subset relationship
# =============================================================================


class TestTBRStructuralInvariants:
    """TBR neighbours are normalised to strict binary trees via
    ``_normalise_binary``; leaf set is preserved."""

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_all_tbr_neighbours_are_binary(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        neighbours = _tbr_only_search()._generate_neighbors(tree)
        for nb in neighbours:
            assert _is_binary(nb), (
                f"TBR neighbour is not strictly binary: {nb.to_newick(branch_lengths=False)}"
            )

    @pytest.mark.parametrize("n", [5, 7, 8, 9])
    def test_tbr_neighbourhood_is_larger_than_nni(self, n: int):
        """A TBR neighbourhood equal to the NNI one means TBR did nothing.

        TBR is a strictly more powerful move than NNI -- NNI is a TBR with the
        cut one level up -- so wherever a TBR neighbourhood is larger, every
        one of those extra topologies is one the search could not have reached
        before.

        This is the only property that detects the walk-direction bug in
        ``TBROperation``. That bug walked DOWN from ``reconnect_node1`` looking
        for ``cut_node1``, which lies below it, so the walk always fell off the
        tree and raised ValueError -- which ``_generate_neighbors`` swallows.
        The neighbours it still produced were all perfectly valid: binary, right
        leaf set, symmetric, no duplicates. Every other test in this file
        passed with the bug restored.

        What it produced was a TBR neighbourhood *identical in size to the NNI
        one* at every n: 4/4, 4/4, 8/8, 10/10, 12/12 for n = 5..9. The search
        was silently running NNI twice. With the walk direction corrected the
        counts are 6, 4, 16, 20, 34 -- strictly larger than NNI wherever a
        larger neighbourhood is reachable at all.

        n = 6 is excluded because the two coincide there even when the code is
        correct; 4 is excluded because both are empty for want of an internal
        edge.
        """
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        nni_count = len(_nni_only_search()._generate_neighbors(tree))
        tbr_count = len(_tbr_only_search()._generate_neighbors(tree))
        assert tbr_count > nni_count, (
            f"n={n}: TBR reached {tbr_count} topologies, the same as the "
            f"NNI-only neighbourhood ({nni_count}) -- the TBR operator "
            f"contributed nothing, which is the signature of the "
            f"walk-direction bug"
        )

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_all_tbr_neighbours_have_same_leaf_set(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        neighbours = _tbr_only_search()._generate_neighbors(tree)
        for nb in neighbours:
            assert set(nb.leaf_names) == set(labels), (
                f"TBR neighbour dropped/added taxa: in={set(labels)} out={set(nb.leaf_names)}"
            )

    @pytest.mark.parametrize("n", [4, 5, 6, 7, 8])
    def test_no_tbr_neighbour_equals_input(self, n: int):
        """TBR is a genuine rearrangement: input must not be in its own
        TBR neighbourhood (the implementation only retains distinct Newicks
        in the dedup step)."""
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)
        orig_newick = tree.to_newick()
        neighbours = _tbr_only_search()._generate_neighbors(tree)
        for nb in neighbours:
            assert nb.to_newick() != orig_newick, (
                f"TBR returned the input tree unchanged; n = {n}"
            )


class TestTBRSymmetry:
    """If B is reachable from A by TBR in the production code, then A is
    reachable from B.

    This is *exactly* testable: for every TBR neighbour B of A, ask whether
    A (by its unrooted-splits signature) appears among B's TBR neighbours.
    A relation that is symmetric on the production-code's subset of TBR is
    the strongest evidence that the operator's reconnect logic is actually
    invertible -- a non-symmetric TBR would indicate the cut/reconnect
    bookkeeping has a hidden one-way bias.
    """

    @pytest.mark.parametrize("n", [5, 6, 7])
    def test_tbr_is_symmetric(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)

        tbr_neighbors = _tbr_only_search(seed=42)._generate_neighbors(tree)
        assert tbr_neighbors, "TBR neighbourhood was empty for n >= 5"

        orig_splits = R.unrooted_splits(tree)
        # For every TBR-reachable B, build B's own TBR neighbourhood and
        # check that A (by unrooted splits) is among them.
        violations = 0
        for nb in tbr_neighbors:
            back = _tbr_only_search(seed=42)._generate_neighbors(nb)
            back_splits = {R.unrooted_splits(t) for t in back}
            if orig_splits not in back_splits:
                violations += 1
        assert violations == 0, (
            f"TBR symmetry violated for n = {n}: {violations} of "
            f"{len(tbr_neighbors)} neighbours did not reach back"
        )


class TestNNIisSubsetOfTBR:
    """Every NNI move (by unrooted topology) is also reachable via the
    production code's TBR.

    NNI is a special case of TBR (the second cut is taken at the parent of
    ``cut_node1``).  Therefore for every topology reachable by NNI there must
    exist a TBR sequence producing it.  We verify the *production code's*
    TBR generator still reaches every NNI topology.
    """

    @pytest.mark.parametrize("n", [5, 6, 7])
    def test_nni_topologies_in_tbr_neighbourhood(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        tree = _binary_tree(labels, seed=42)

        nni_neighbors = _nni_only_search(seed=42)._generate_neighbors(tree)
        tbr_neighbors = _tbr_only_search(seed=42)._generate_neighbors(tree)

        nni_splits = {R.unrooted_splits(t) for t in nni_neighbors}
        tbr_splits = {R.unrooted_splits(t) for t in tbr_neighbors}

        # NNI includes "self" topologies for the root edge (the swap that
        # re-roots to the same unrooted tree); discard self-splits before
        # checking the subset relation.
        nni_new = nni_splits - {R.unrooted_splits(tree)}
        missing = nni_new - tbr_splits
        assert not missing, (
            f"NNI topologies missing from TBR for n = {n}: {missing}"
        )


# =============================================================================
# HeuristicSearch -- high-level invariants
# =============================================================================


class TestSearchReproducibility:
    """Same seed => identical best tree and best score across runs."""

    def test_same_seed_same_best_tree(self):
        labels = ["A", "B", "C", "D", "E"]
        sequences = _divergent_sequences(labels)

        s1 = HeuristicSearch(max_iterations=10, random_seed=42, nni_swap_probability=1.0)
        r1 = s1.search(labels, sequences)
        s2 = HeuristicSearch(max_iterations=10, random_seed=42, nni_swap_probability=1.0)
        r2 = s2.search(labels, sequences)

        assert r1.best_tree.to_newick() == r2.best_tree.to_newick()
        assert r1.best_score == r2.best_score

    def test_different_seeds_still_run_cleanly(self):
        """Different seeds may explore differently but must complete."""
        labels = ["A", "B", "C", "D", "E"]
        sequences = _divergent_sequences(labels)
        results = []
        for seed in (1, 2, 3):
            s = HeuristicSearch(max_iterations=10, random_seed=seed, nni_swap_probability=1.0)
            r = s.search(labels, sequences)
            results.append(r)
        for r in results:
            assert r.best_tree is not None
            assert r.best_score >= 0
            assert set(r.best_tree.leaf_names) == set(labels)

    def test_run_heuristic_search_convenience(self):
        """``run_heuristic_search`` should return a valid SearchResult."""
        labels = ["A", "B", "C", "D", "E"]
        sequences = _uniform_sequences(labels)
        result = run_heuristic_search(labels, sequences, max_iterations=5)
        assert isinstance(result, SearchResult)
        assert result.best_tree is not None
        assert set(result.best_tree.leaf_names) == set(labels)
        assert result.best_score >= 0


class TestSearchNonMutation:
    """The search loop must not mutate the initial_tree passed in by the
    caller.  This is the classic silent-corruption bug: the operator deep-
    copies, but the search bookkeeping forgets to, and the next iteration
    starts from a half-edited tree.
    """

    def test_input_tree_newick_preserved(self):
        labels = ["A", "B", "C", "D", "E"]
        sequences = _divergent_sequences(labels)
        tree = _binary_tree(labels, seed=42)
        before_newick = tree.to_newick()

        s = HeuristicSearch(max_iterations=5, random_seed=42)
        s.search(labels, sequences, initial_tree=tree)

        assert tree.to_newick() == before_newick

    def test_input_root_object_identity_preserved(self):
        labels = ["A", "B", "C", "D", "E"]
        sequences = _divergent_sequences(labels)
        tree = _binary_tree(labels, seed=42)
        root_id_before = id(tree.root)

        s = HeuristicSearch(max_iterations=5, random_seed=42)
        s.search(labels, sequences, initial_tree=tree)

        assert id(tree.root) == root_id_before


class TestSearchLeafConservation:
    """No taxon may be added or lost across the whole search."""

    def test_result_has_all_input_taxa(self):
        labels = ["A", "B", "C", "D", "E", "F"]
        sequences = _divergent_sequences(labels)
        result = HeuristicSearch(max_iterations=10, random_seed=42).search(labels, sequences)
        assert set(result.best_tree.leaf_names) == set(labels)

    def test_leaf_set_unchanged_throughout_search(self):
        """Every leaf name passed in must appear in every generated neighbour."""
        labels = ["A", "B", "C", "D", "E", "F"]
        tree = _binary_tree(labels, seed=42)
        s = HeuristicSearch(max_iterations=10, random_seed=42)
        neighbours = s._generate_neighbors(tree)
        for nb in neighbours:
            assert set(nb.leaf_names) == set(labels), (
                f"neighbour dropped taxa: in={set(labels)} out={set(nb.leaf_names)}"
            )


class TestSearchScoreSanity:
    """Parsimony (Fitch) tree length is a non-negative integer count.
    Best score must be finite and at most the starting score (the search
    returns the minimum score it saw).
    """

    def test_best_score_is_finite_and_non_negative(self):
        labels = ["A", "B", "C", "D", "E"]
        sequences = _divergent_sequences(labels)
        result = HeuristicSearch(max_iterations=10, random_seed=42).search(labels, sequences)
        assert result.best_score >= 0
        assert result.best_score != float("inf")

    def test_initial_tree_best_when_uniform(self):
        """If all sequences are identical, parsimony is 0 on ANY tree.

        The search should not degrade the score below 0 (parsimony is a
        count of changes) -- here we use it as a regression tripwire for
        sign flips or sign errors in the score comparison logic.
        """
        labels = ["A", "B", "C", "D", "E"]
        sequences = {name: "AAAAAAAA" for name in labels}
        result = HeuristicSearch(max_iterations=5, random_seed=42).search(labels, sequences)
        assert result.best_score == 0.0


class TestSearchResultConsensusProperty:
    """When the search returns a single optimal tree, ``consensus_tree``
    should be None (there is nothing to compute a consensus of)."""

    def test_single_tree_consensus_is_none(self):
        labels = ["A", "B", "C", "D", "E"]
        sequences = _uniform_sequences(labels)
        result = HeuristicSearch(max_iterations=5, random_seed=42).search(labels, sequences)
        # The all-zero-score case frequently ends with one optimal tree.
        assert len(result.all_trees) >= 1
        if len(result.all_trees) == 1:
            assert result.consensus_tree is None


# =============================================================================
# _build_random_tree -- basic shape contract
# =============================================================================


class TestBuildRandomTree:
    """``_build_random_tree`` must produce a strictly binary tree over the
    given leaf names.  It is the default starting point for ``search``."""

    @pytest.mark.parametrize("n", [3, 4, 5, 6, 7])
    def test_random_tree_is_binary_with_given_leaves(self, n: int):
        labels = [chr(ord("A") + i) for i in range(n)]
        s = HeuristicSearch(random_seed=42)
        for _ in range(3):
            tree = s._build_random_tree(labels)
            assert _is_binary(tree), f"random tree not binary for n = {n}"
            assert set(tree.leaf_names) == set(labels), (
                f"random tree dropped/added taxa: in={set(labels)} out={set(tree.leaf_names)}"
            )

    def test_random_tree_uses_instance_rng(self):
        """Two calls on the same instance should be reproducible (seed)."""
        labels = ["A", "B", "C", "D", "E", "F"]
        s1 = HeuristicSearch(random_seed=2025)
        s2 = HeuristicSearch(random_seed=2025)
        t1 = s1._build_random_tree(labels)
        t2 = s2._build_random_tree(labels)
        assert t1.to_newick() == t2.to_newick()


# =============================================================================
# _collect_internal_edges -- what it actually returns
# =============================================================================
#
# NOTE: the production code's ``_collect_internal_edges`` returns *every*
# edge incident to an internal node, including pendant edges from an internal
# node to a leaf.  The function name is therefore misleading: the set is
# "edges incident to internal nodes", not "edges between two internal nodes".
# The downstream operators (NNI, TBR) cope correctly by filtering/rejecting
# pendant edges -- but the function's contract should be documented and
# ideally fixed.  We pin the actual behaviour here so a future "fix" that
# tightens the filter is observed.


class TestCollectInternalEdges:
    def test_includes_only_edges_with_internal_parent(self):
        labels = ["A", "B", "C", "D", "E"]
        tree = _binary_tree(labels, seed=42)
        s = HeuristicSearch(random_seed=42)
        edges = s._collect_internal_edges(tree.root)
        # Every collected edge has the parent endpoint non-leaf.
        for parent, _child in edges:
            assert not parent.is_leaf, (
                f"edge has a leaf parent: parent={parent.name}"
            )


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-v"]))
