"""cx_Freeze build for the MSI installer.

Why a second tool: PyInstaller cannot produce an MSI, and an MSI is what makes
the program installable rather than merely runnable -- an entry under
Installed Apps, a Start Menu shortcut, an uninstaller, and a version the
Programs list can show. cx_Freeze emits both the frozen tree and the installer
from one description.

The frozen build uses the same base name as the PyInstaller one, because only
one of the two is shipped: cx_Freeze's tree is an intermediate for the MSI and
is deleted afterwards. Shipping both would mean two subtly different builds
under one name.

Version pin: cx_Freeze 8.x dropped numpy 1.x -- its numpy hook looks for
``numpy._core._exceptions``, a 2.x path -- and this environment is on 1.26.4.
7.2.2 is the release that still handles numpy 1.x.

Run:  python packaging/build_msi.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DIST = PROJECT_ROOT / "dist"

VERSION = "1.1.1"
PRODUCT_NAME = "PaleoAST"
ORG_NAME = "PaleoAST Development Team"
DESCRIPTION = (
    "PaleoAST -- Paleontological Advanced Statistical Toolkit. Multivariate, "
    "morphometric, phylogenetic and macroevolutionary analysis for "
    "paleontological data."
)

# Frozen into a temp directory rather than one under the project.
# bdist_msi re-visits the build tree to embed it, and on Windows that revisit
# reproducibly failed with
#   [Errno 13] Permission denied: ...\dist\PaleoAST-msi-build
# immediately after the last include was copied -- the tree cx_Freeze had just
# written and was still holding open, and which the scanner was still reading.
BUILD_DIR = Path(tempfile.gettempdir()) / "paleoast-msi-frozen"


def ensure_cx_freeze() -> None:
    probe = subprocess.run([sys.executable, "-c", "import cx_Freeze"], capture_output=True)
    if probe.returncode != 0:
        print("installing cx_Freeze...")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", "cx_Freeze==7.2.2"],
            check=True,
        )


SETUP_TEMPLATE = """# Generated by packaging/build_msi.py -- edit that file, not this one.
#
# Self-contained on purpose: cx_Freeze execs this file, so it must not depend
# on a name defined by its generator. The sys.path entry is not optional
# either -- cx_Freeze's module finder walks the path itself, and without the
# project root it cannot import this project's own packages
# ("No module named 'visualization.r_export'").
import os
import sys

from cx_Freeze import Executable, setup

PROJECT_ROOT = {root!r}
if not os.path.isabs(PROJECT_ROOT):
    PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

setup(
    name={product!r},
    version={version!r},
    description={description!r},
    long_description={description!r},
    author={author!r},
    license="MIT",
    url="https://github.com/syxscott/PaleoAST",
    options={{
        "build_exe": {{
            "build_exe": {build_dir!r},
            "packages": [
                "config", "controllers", "data", "ecology", "models",
                "morphometrics", "macroevolution", "parsers", "phylogenetics",
                "stats", "stratigraphy", "utils", "visualization", "views",
            ],
            "includes": [
                "PyQt6", "numpy", "scipy", "pandas", "matplotlib", "psutil",
                # Reached only through a local import inside the main window,
                # so nothing in the module graph mentions them.
                "visualization.r_export",
                "visualization.r_render",
                "config.i18n.translations_en",
                "config.i18n.translations_zh",
            ],
            "include_files": [
                ("data", "data"),
                ("config/i18n", "config/i18n"),
                ("logo.png", "."),
            ],
            # Same reasoning as the PyInstaller spec: none of these is imported
            # by the project, and the first build carried 680 MB of them.
            "excludes": [
                "tkinter", "pytest", "IPython", "notebook", "jupyter",
                "torch", "torchvision", "cv2", "polars",
                "_polars_runtime_32", "_polars_runtime_64",
                "bitsandbytes", "pyarrow", "tensorflow", "jax", "numba",
                "h5py", "nvidia", "triton",
            ],
            "optimize": 0,
        }},
        "bdist_msi": {{
            "upgrade_code": "{{8B4A5C71-1D6E-4E3B-9F27-6C1A2D5E7B03}}",
            "add_to_path": True,
            "initial_target_dir": r"\\\\Program Files\\\\PaleoAST",
        }},
    }},
    executables=[
        Executable(
            script=os.path.join(PROJECT_ROOT, "main.py"),
            base="Win32GUI",
            target_name="PaleoAST.exe",
            icon=os.path.join(PROJECT_ROOT, "logo.png"),
            shortcut_name="PaleoAST",
            shortcut_dir="DesktopFolder",
        ),
    ],
)
"""


def write_setup() -> Path:
    target = PROJECT_ROOT / "packaging" / "cx_freeze_setup.py"
    target.write_text(
        SETUP_TEMPLATE.format(
            root=str(PROJECT_ROOT),
            product=PRODUCT_NAME,
            version=VERSION,
            description=DESCRIPTION,
            author=ORG_NAME,
            build_dir=str(BUILD_DIR),
        ),
        encoding="utf-8",
    )
    return target


def main() -> int:
    ensure_cx_freeze()
    setup_py = write_setup()
    print(f"cx_Freeze setup: {setup_py}")
    print(f"frozen tree:    {BUILD_DIR}")

    for stale in (BUILD_DIR,):
        if stale.exists():
            shutil.rmtree(stale, ignore_errors=True)
    for old in DIST.glob("*.msi"):
        old.unlink()

    print("building the MSI (freezing, then compiling)...")
    result = subprocess.run([sys.executable, str(setup_py), "bdist_msi"], cwd=str(PROJECT_ROOT))
    if result.returncode != 0:
        print("MSI build failed")
        return 1

    built = sorted(DIST.glob("*.msi"))
    if not built:
        print("bdist_msi reported success but produced no .msi")
        return 1
    for msi in built:
        print(f"  {msi}  {msi.stat().st_size / 1024 / 1024:.1f} MB")
    # The frozen tree is an intermediate for the MSI, not a deliverable.
    shutil.rmtree(BUILD_DIR, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
