# Generated by packaging/build_msi.py -- edit that file, not this one.
#
# Self-contained on purpose: cx_Freeze execs this file, so it must not depend
# on a name defined by its generator. The sys.path entry is not optional
# either -- cx_Freeze's module finder walks the path itself, and without the
# project root it cannot import this project's own packages
# ("No module named 'visualization.r_export'").
import os
import sys

from cx_Freeze import Executable, setup

PROJECT_ROOT = "D:\\GIthub\\PaleoAST"
if not os.path.isabs(PROJECT_ROOT):
    PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

setup(
    name="PaleoAST",
    version="1.1.0",
    description="PaleoAST -- Paleontological Advanced Statistical Toolkit. Multivariate, morphometric, phylogenetic and macroevolutionary analysis for paleontological data.",
    long_description="PaleoAST -- Paleontological Advanced Statistical Toolkit. Multivariate, morphometric, phylogenetic and macroevolutionary analysis for paleontological data.",
    author="PaleoAST Development Team",
    license="MIT",
    url="https://github.com/syxscott/PaleoAST",
    options={
        "build_exe": {
            "build_exe": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\paleoast-msi-frozen",
            "packages": [
                "config",
                "controllers",
                "data",
                "ecology",
                "models",
                "morphometrics",
                "macroevolution",
                "parsers",
                "phylogenetics",
                "stats",
                "stratigraphy",
                "utils",
                "visualization",
                "views",
            ],
            "includes": [
                "PyQt6",
                "numpy",
                "scipy",
                "pandas",
                "matplotlib",
                "psutil",
                # Reached only through a local import inside the main window,
                # so nothing in the module graph mentions them.
                "visualization.r_export",
                "visualization.r_render",
                "config.i18n.translations_en",
                "config.i18n.translations_zh",
            ],
            "include_files": [
                ("data", "data"),
                ("config/i18n", "config/i18n"),
                ("logo.png", "."),
            ],
            # Same reasoning as the PyInstaller spec: none of these is imported
            # by the project, and the first build carried 680 MB of them.
            "excludes": [
                "tkinter",
                "pytest",
                "IPython",
                "notebook",
                "jupyter",
                "torch",
                "torchvision",
                "cv2",
                "polars",
                "_polars_runtime_32",
                "_polars_runtime_64",
                "bitsandbytes",
                "pyarrow",
                "tensorflow",
                "jax",
                "numba",
                "h5py",
                "nvidia",
                "triton",
            ],
            "optimize": 0,
        },
        "bdist_msi": {
            "upgrade_code": "{8B4A5C71-1D6E-4E3B-9F27-6C1A2D5E7B03}",
            "add_to_path": True,
            "initial_target_dir": r"\\Program Files\\PaleoAST",
        },
    },
    executables=[
        Executable(
            script=os.path.join(PROJECT_ROOT, "main.py"),
            base="Win32GUI",
            target_name="PaleoAST.exe",
            icon=os.path.join(PROJECT_ROOT, "logo.png"),
            shortcut_name="PaleoAST",
            shortcut_dir="DesktopFolder",
        ),
    ],
)
