"""Generate the WiX component list from the built tree.

The payload is ~2,400 files and its exact composition changes with every
build, so a hand-written list would ship an installer missing whatever was
added last. This walks dist/PaleoAST and emits real File elements, grouped
into components of at most 50 -- WiX's limit per component, and exceeding it
is an ICE error rather than a warning.

Emits a fragment included by packaging/PaleoAST.wxs:

    candle -dPaleoAST.wixobj -out obj packaging/PaleoAST.wxs
    light  -ext WixUIExtension -out dist/PaleoAST-1.1.2-windows-x64.msi obj/PaleoAST.wixobj

Run:  python packaging/harvest_payload.py
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PAYLOAD = PROJECT_ROOT / "dist" / "PaleoAST"
OUT = PROJECT_ROOT / "packaging" / "_payload.wxs"

# WiX refuses a component with more than 50 File elements.
MAX_FILES_PER_COMPONENT = 50
# WiX identifiers: ASCII letters, digits, underscore and period, and the first
# character must be a letter or an underscore. The payload contains names like
# "attrs-26.1.0.dist-info", whose hyphens are illegal, so every path segment
# is sanitised rather than rejected.
ID_ALLOWED = re.compile(r"[^A-Za-z0-9_.]")


def wid(path: str) -> str:
    """A unique, legal File identifier.

    Sanitising alone is not enough: "GMT" and "GMT+0" both become "GMT_0",
    and "GMT+1" and "GMT+10" differ only by a digit, so the payload contains
    several collisions that light reports as LGHT0091 Duplicate symbol. A short
    hash of the original path keeps the readable prefix for humans and makes
    the id unique for WiX.
    """
    digest = hashlib.sha1(path.encode("utf-8")).hexdigest()[:8]
    cleaned = ID_ALLOWED.sub("_", path)
    if not cleaned or not (cleaned[0].isalpha() or cleaned[0] == "_"):
        cleaned = "_" + cleaned
    # 72 characters is WiX's standard identifier length; stay well under it.
    prefix = cleaned[:60]
    return f"f_{prefix}_{digest}"


def did(rel: Path) -> str:
    key = "/".join(rel.parts)
    digest = hashlib.sha1(key.encode("utf-8")).hexdigest()[:8]
    prefix = "__".join(ID_ALLOWED.sub("_", part) for part in rel.parts)[:50]
    return f"d_{prefix}_{digest}"


def esc(text) -> str:
    """XML-escape. The build tree lives under 'D:\\Program Files\\...', so the
    ampersand is not hypothetical -- and it has to be replaced first, or it
    turns the escapes of the other two into entities of their own."""
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def component_guid(name: str) -> str:
    """A deterministic GUID so the same file keeps the same component.

    WiX can auto-generate one, but it does that per *build*, and an auto GUID
    that changes on upgrade makes Windows Installer treat the new component as
    a different one -- which is how a 361 MB reinstall ends up as two copies.
    """
    digest = hashlib.sha256(name.encode("utf-8")).hexdigest().upper()
    return f"{{{digest[0:8]}-{digest[8:12]}-{digest[12:16]}-{digest[16:20]}-{digest[20:32]}}}"


def main() -> int:
    if not (PAYLOAD / "PaleoAST.exe").is_dir() and not (PAYLOAD / "PaleoAST.exe").exists():
        print(f"no build found at {PAYLOAD}")
        return 1

    files: list[Path] = sorted(p for p in PAYLOAD.rglob("*") if p.is_file())
    print(f"harvesting {len(files)} files from {PAYLOAD}")

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- GENERATED by packaging/harvest_payload.py. Do not edit. -->",
        '<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">',
        "  <Fragment>",
    ]

    # Directories as a nested tree. WiX needs each child declared inside its
    # parent: a flat list of every directory in the payload is rejected with
    # "not a valid root directory", because a top level Directory is the
    # product root and there may be only one of those.
    dir_ids: dict[Path, str] = {PAYLOAD: "INSTALLFOLDER"}
    # Every ancestor below the payload root, not just the direct parent of each
    # file: the tree has directories that contain only subdirectories, and a
    # DirectoryRef naming one of those as its parent would have no id to use.
    all_dirs: set[Path] = set()
    for p in files:
        for parent in p.parents:
            if parent == PAYLOAD:
                break
            all_dirs.add(parent)
    # Walk by depth so a parent is always emitted before its children.
    for d in sorted(all_dirs, key=lambda q: (len(q.parts), str(q))):
        dir_ids[d] = did(d.relative_to(PAYLOAD))

    def emit_dir(d: Path, indent: str) -> None:
        """One DirectoryRef per directory, each naming its own parent.

        WiX 3 cannot declare a directory tree inside a Fragment by nesting: a
        bare Directory at fragment top level is read as a product root
        (CNDL0205), and a DirectoryRef nested inside a Directory is rejected
        (CNDL0005). A flat list satisfies both, and is what the IDE generates
        for a harvested project.
        """
        lines.append(f'{indent}<DirectoryRef Id="{dir_ids[d.parent]}">')
        lines.append(f'{indent}  <Directory Id="{dir_ids[d]}" Name="{esc(d.name)}" />')
        lines.append(f"{indent}</DirectoryRef>")

    # Flat, ordered by depth so a parent is always declared before any
    # DirectoryRef that points at it.
    for d in sorted(
        (c for c in dir_ids if c != PAYLOAD),
        key=lambda q: (len(q.parts), str(q)),
    ):
        emit_dir(d, "    ")

    # Everything inside the payload -- including PaleoAST.exe -- lives in one
    # ComponentGroup that the Feature references. A second component claiming
    # the exe would put one file in two components, which ICE rejects.
    lines.append('    <ComponentGroup Id="Payload">')
    comp_index = 0
    for d in [PAYLOAD, *[c for c in dir_ids if c != PAYLOAD]]:
        here = [p for p in files if p.parent == d]
        if not here:
            continue
        dir_ident = dir_ids[d]
        for start in range(0, len(here), MAX_FILES_PER_COMPONENT):
            chunk = here[start : start + MAX_FILES_PER_COMPONENT]
            comp_index += 1
            comp_id = f"C{comp_index:04d}"
            key = chunk[0].relative_to(PAYLOAD).as_posix()
            lines.append(f'      <Component Id="{comp_id}" Directory="{dir_ident}" Guid="{component_guid(key)}">')
            for f in chunk:
                rel = f.relative_to(PAYLOAD).as_posix()
                # Name is what lands on disk; Source is what gets read. They
                # differ only when the tree holds a path WiX would normalise,
                # so keep both explicit.
                #
                # A component needs exactly one keypath, and Windows Installer
                # cannot repair or uninstall a component without one. With 50
                # files per component, WiX only infers it when a component holds
                # a single file, so the first of each chunk is marked here.
                keypath = ' KeyPath="yes"' if f is chunk[0] else ""
                lines.append(f'        <File Id="{wid(rel)}" Name="{esc(f.name)}" Source="{esc(f)}"{keypath} />')
            lines.append("      </Component>")
    lines.append("    </ComponentGroup>")

    lines.append("  </Fragment>")
    lines.append("</Wix>")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {OUT} -- {comp_index} components, {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
